# Generated by Django 4.0.6 on 2022-12-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autists',
            name='badOpinion',
            field=models.TextField(default='gordo rancio'),
        ),
        migrations.AddField(
            model_name='autists',
            name='goodOpinion',
            field=models.TextField(default='cogible'),
        ),
    ]
