# Generated by Django 4.0.6 on 2022-12-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_autists_badopinion_autists_goodopinion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unamed', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='autists',
            name='name',
        ),
    ]
