# Generated by Django 4.0.6 on 2022-12-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_names_remove_autists_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='autists',
            name='name',
            field=models.CharField(default='unamed', max_length=255),
        ),
    ]
