# Generated by Django 4.0.6 on 2022-12-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_alter_autists_badopinion_alter_autists_goodopinion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autists',
            name='badOpinion',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='autists',
            name='goodOpinion',
            field=models.TextField(max_length=255),
        ),
    ]
